#!/usr/bin/env python3
"""Build the Amiga logo assets from images/config-nio-160x96x4.png.

The artwork has square pixels; Workbench hires pixels are about twice as
tall as they are wide, so the logo is resampled to half as many rows as
columns.  Connected shapes reaching left of SPLIT_X form the emblem (its
lines run under the lettering), the remaining glyphs the lettering;
the two become separate 1-bit masks so the program can draw them in the
screen's own pens (see amiga_gui.c) and the icon can use pen 3 / pen 1.

Outputs (checked in; a normal build needs neither Python nor Pillow):
  src/platform/amiga/amiga_logo_data.c   84x27 masks for the window
  amiga/gfx/config-nio.icon.txt           96x30 art for tools/mkinfo.py

Usage (from the repository root): python3 amiga/tools/mklogo.py
"""

from PIL import Image

SOURCE = "images/config-nio-160x96x4.png"
SPLIT_X = 85          # first column of the "FUJI" lettering in SOURCE
THRESHOLD = 0.35      # fraction of lit source pixels that lights a cell
WINDOW = (84, 27)
ICON = (96, 30)


def text_pixels(img):
    """Lit source pixels that belong to the lettering, not the emblem."""
    sw, sh = img.size
    lit = {(x, y) for x in range(sw) for y in range(sh)
           if img.getpixel((x, y)) > 128}
    emblem = set()
    stack = [p for p in lit if p[0] < SPLIT_X]
    while stack:
        p = stack.pop()
        if p in emblem:
            continue
        emblem.add(p)
        x, y = p
        for q in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if q in lit and q not in emblem:
                stack.append(q)
    return lit - emblem


def resample(img, w, h, text):
    """Return rows of (lit, is_text) cells for a w x h resampling."""
    sw, sh = img.size
    sx, sy = sw / w, sh / h
    rows = []
    for j in range(h):
        row = []
        y0, y1 = int(j * sy), max(int((j + 1) * sy), int(j * sy) + 1)
        for i in range(w):
            x0, x1 = int(i * sx), max(int((i + 1) * sx), int(i * sx) + 1)
            cells = [(x, y) for x in range(x0, x1) for y in range(y0, y1)
                     if img.getpixel((x, y)) > 128]
            on = len(cells) / ((x1 - x0) * (y1 - y0)) >= THRESHOLD
            is_text = sum(1 for c in cells if c in text) * 2 > len(cells)
            row.append((on, is_text))
        rows.append(row)
    return rows


def words(rows, want_text):
    w = len(rows[0])
    per_row = (w + 15) // 16
    out = []
    for row in rows:
        bits = [on and is_text == want_text for on, is_text in row]
        bits += [False] * (per_row * 16 - w)
        for k in range(per_row):
            value = 0
            for b in bits[k * 16:(k + 1) * 16]:
                value = (value << 1) | int(b)
            out.append(value)
    return out, per_row


def c_array(name, data, per_row):
    lines = [f"const uint16_t {name}[AMIGA_LOGO_WORDS * AMIGA_LOGO_H] = {{"]
    for r in range(0, len(data), per_row):
        lines.append("  " + ", ".join(f"0x{v:04X}" for v in data[r:r + per_row]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    img = Image.open(SOURCE).convert("L")
    lettering = text_pixels(img)

    rows = resample(img, *WINDOW, lettering)
    emblem, per_row = words(rows, False)
    text, _ = words(rows, True)
    with open("src/platform/amiga/amiga_logo_data.c", "w") as f:
        f.write("/* Generated by amiga/tools/mklogo.py from " + SOURCE +
                "; do not edit. */\n")
        f.write('#include "amiga_logo.h"\n\n')
        f.write(c_array("amiga_logo_emblem", emblem, per_row) + "\n\n")
        f.write(c_array("amiga_logo_text", text, per_row) + "\n")

    rows = resample(img, *ICON, lettering)
    with open("amiga/gfx/config-nio.icon.txt", "w") as f:
        for row in rows:
            f.write("".join("." if not on else ("W" if t else "O")
                            for on, t in row) + "\n")
    print("wrote amiga_logo_data.c and config-nio.icon.txt")


if __name__ == "__main__":
    main()
