#ifndef AMIGA_LOGO_H_INCLUDED
#define AMIGA_LOGO_H_INCLUDED

#include <stdint.h>

/* FujiNet config-nio logo for the window header, as two 1-bit masks (the
 * emblem and the lettering) so each can be drawn in a screen pen.  Rows are
 * AMIGA_LOGO_WORDS 16-bit words; the MSB is the leftmost pixel.  Data is
 * generated by amiga/tools/mklogo.py. */
#define AMIGA_LOGO_W 84
#define AMIGA_LOGO_H 27
#define AMIGA_LOGO_WORDS ((AMIGA_LOGO_W + 15) / 16)

extern const uint16_t amiga_logo_emblem[AMIGA_LOGO_WORDS * AMIGA_LOGO_H];
extern const uint16_t amiga_logo_text[AMIGA_LOGO_WORDS * AMIGA_LOGO_H];

int amiga_logo_pixel(const uint16_t *mask, uint16_t x, uint16_t y);

#endif
